platform :ios, '8.0'

target 'Neteasemusic' do
    
pod 'AFNetworking'
pod 'MJExtension'
pod 'Masonry', '~> 1.0.1'

end

target 'NeteasemusicTests' do
    
end

target 'NeteasemusicUITests' do
    
end
